repos:
  - repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.6.1
    hooks:
      - id: pre-commit-update

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.3"
    hooks:
      - id: ruff
        args:
          - "--exit-non-zero-on-fix"
      - id: ruff-format

  - repo: https://github.com/pycqa/pylint
    # Cannot be replaced by ruff until https://github.com/astral-sh/ruff/issues/970 is closed
    rev: "v3.3.3"
    hooks:
      - id: pylint
        additional_dependencies:
          - "pytest==8.3.4"
          - "mypy==1.14.1"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.14.1"
    hooks:
      - id: mypy
        additional_dependencies:
          - "pytest==8.3.4"

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: "v9.20.0"
    hooks:
      - id: commitlint
        stages:
          - commit-msg
        additional_dependencies:
          - "@commitlint/config-conventional"
        args:
          - "--config=.commitlintrc.json"
